django2/feed/urls.py
from django.urls import path
from .import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail")
]

django2/til/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path as url
from feed import urls as feed_urls
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    url("", include("allauth.urls")),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django2/feed/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete= models.CASCADE
    )

    def __str__(self):
        return self.text[0:100]

django2/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
        )
    image = ImageField(upload_to='profiles')

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when Django User is created."""
    if created:
        Profile.objects.create(user=instance)

django2/feed/views.py
#from django.shortcuts import render
from django.views.generic import ListView
from .models import Post
from django.db.models.query import QuerySet
from django.views.generic import ListView, DetailView

# Create your views here.

class HomePage(ListView):
    http_method_names= ["get"]
    template_name = "feed/homepage.html"
    model = Post
    context_object_name = "posts"
    QuerySet = Post.objects.all().order_by('-id')[0:30]

class PostDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "feed/detail.html"
    model = Post
    context_object_name = "post{{ post }}"

django2/profiles/views.py
from django.shortcuts import render

# Create your views here.

django2/feed/templates/feed/detail.html
{% extends "base.html"%}
{% load thumbnail%}

{% block body %}

   <!-- component is from https://www.creative-tim.com/twcomponents/component/post-artical -->
   <div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style="width: 50rem;">
    <div class="flex justify-between items-center">
    <span class="font-light text-gray-600">{{post.date}}</span>
    <!--a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">Design</-a-->
    </div>
    <div class="mt-2">
    <!--a class="text-2xl text-gray-700 font-bold hover:text-gray-600" href="#">Accessibility tools for designers and developers</!--a-->
    <p class="mt-2 text-gray-600">{{ post.text}}</p>
    </div>
    <div class="flex justify-between items-center mt-4">
    <div>

         {#TODO: user details#}
         <a class="flex items-center" href="#">
                {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                  <!--img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"!-->
                  <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{im.url}}" alt="avatar">
                {% endthumbnail %}
              <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
         </a>
    </div>
    </div>
</div>



{% endblock body%}

django2/feed/templates/feed/homepage.html
{% extends "base.html" %}
{% load thumbnail %}

{%block title%} Changed the title of the homepage {%endblock%}

{% block body %}

     {% for post in posts%}

          <!-- component is from https://www.creative-tim.com/twcomponents/component/post-artical -->
          <div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style="width: 50rem;">
               <div class="flex justify-between items-center">
               <span class="font-light text-gray-600">{{post.date}}</span>
               <!--a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">Design</-a-->
               </div>
               <div class="mt-2">
               <!--a class="text-2xl text-gray-700 font-bold hover:text-gray-600" href="#">Accessibility tools for designers and developers</!--a-->
               <p class="mt-2 text-gray-600">{{ post.text}}</p>
               </div>
               <div class="flex justify-between items-center mt-4">

               <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">Read more</a>
               <div>

                    {#TODO: user details#}
                    <a class="flex items-center" href="#">
                           {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                             <!--img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"!-->
                             <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{im.url}}" alt="avatar">
                           {% endthumbnail %}
                         <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
                    </a>
               </div>
               </div>
          </div>

     {%endfor%}

{% endblock %}

django2/til/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title in here{% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
</head>
<body>

<!-- component is from https://tailwindcomponents.com/component/sidebar-navigation -->
<div class="min-h-screen flex flex-row bg-gray-100">
  <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
    <div class="flex items-center justify-center h-20 shadow-md">
      <h1 class="text-3xl uppercase text-indigo-500">TIL</h1>
    </div>
    <ul class="flex flex-col py-4">
      <li>
        <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
          <span class="text-sm font-medium">Home</span>
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li>
            <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
            <span class="text-sm font-medium">Logout</span>
            </a>
        </li>
      {% else %}
        <li>
            <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
            <span class="text-sm font-medium">Login</span>
            </a>
        </li>
      {% endif %}
    </ul>
  </div>
  <div class="p-16">
    {% block body %}
        {% block content %}{% endblock %}
    {% endblock %}
  </div>
</div>

</body>
</html>